[project]
name = "pythonproject3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "google-api-python-client>=2.188.0",
    "google-auth-oauthlib>=1.2.4",
    "requests>=2.32.5",
]
